# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Topics
  version: 
  folders:

  - title: TEST
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf

    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
      output: web

    - title: Sample 1
      url: /p1_sample1.html
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.html
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.html
      output: web, pdf

  - title: Getting started
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf

  - title: Projects
    output: web, pdf

    folderitems:
    - title: Cha
      url: /p1_sample4.html
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.html
      output: web, pdf

    - title: Bernie
      url: /bernie.html
      output: web, pdf

  - title: Cost Management Sheet (CMS)
    output: web, pdf

    folderitems:
    - title: Cha
      url: /p1_sample4.html
      output: web, pdf

  - title: Master Data
    output: web, pdf

    folderitems:
    - title: Cha 2
      url: /p1_sample4.html
      output: web, pdf

  - title: Admin
    output: web, pdf

    folderitems:
    - title: Cha 2
      url: /p1_sample1.html
      output: web, pdf

  - title: Mobile app
    output: web, pdf

    folderitems:
    - title: Cha 2
      url: /p1_sample1.html
      output: web, pdf

  - title: FAQs
    output: web, pdf

    folderitems:
    - title: Houses
      url: /spark_houses.html
      output: web, pdf